const menu = [
  {
    id: 1,
    name: "Doro Wat",
    price: 240,
    category: "Main",
    spicy: true,
    image: "/images/doro-wet.jpg",
    description: "Spicy Ethiopian chicken stew with berbere",
  },
  {
    id: 2,
    name: "Buna",
    price: 80,
    category: "Drink",
    spicy: false,
    image: "/images/buna.jpg",
    description: "Traditional Ethiopian coffee",
  },
  {
    id: 3,
    name: "Shiro",
    price: 150,
    category: "Main",
    spicy: false,
    image: "/images/shiro.jpg",
    description: "Traditional Ethiopian chickpea stew",
  },
  {
    id: 4,
    name: "Tibs",
    price: 250,
    category: "Main",
    spicy: true,
    image: "/images/tibs.jpg",
    description: "Sautéed beef with vegetables",
  },
  {
    id: 5,
    name: "Chechebsa",
    price: 120,
    category: "Breakfast",
    spicy: false,
    image: "/images/chechebsa.jpg",
    description: "Traditional Ethiopian breakfast with torn flatbread",
  },
  {
    id: 6,
    name: "Firfir",
    price: 140,
    category: "Breakfast",
    spicy: true,
    image: "/images/firfir.jpg",
    description: "Injera pieces mixed with berbere sauce",
  },
  {
    id: 7,
    name: "Dabo",
    price: 100,
    category: "Breakfast",
    spicy: false,
    image: "/images/dabo.jpg",
    description: "Traditional Ethiopian homemade bread",
  },
  {
    id: 8,
    name: "Beyaynetu",
    price: 220,
    category: "Main",
    spicy: false,
    image: "/images/beyaynetu.jpg",
    description: "Assorted vegetarian Ethiopian dishes",
  },
  {
    id: 9,
    name: "Fetira",
    price: 130,
    category: "Breakfast",
    spicy: false,
    image: "/images/fetira.jpg",
    description: "Crispy Ethiopian layered flatbread",
  },
  {
    id: 10,
    name: "Baklava",
    price: 160,
    category: "Dessert",
    spicy: false,
    image: "/images/baklava.jpg",
    description: "Sweet layered pastry with nuts and syrup",
  },
];

export default menu;